<<<<<<< SEARCH
    const validTransitions = {
      DRAFT: ["PENDING_MATCH", "PENDING_INSTITUTION"],
      PENDING_MATCH: ["PENDING_INSTITUTION", "DRAFT"],
      PENDING_INSTITUTION: ["PENDING_COORDINATOR", "DRAFT"],
      PENDING_COORDINATOR: ["ACTIVE", "DRAFT"],
      ACTIVE: ["EVALUATION"],
      EVALUATION: ["CLOSED"],
      CLOSED: ["FINAL_EXAM"],
      PENDING_ORG_APPROVAL: ["ORG_APPROVED", "REJECTED"],
      ORG_APPROVED: ["ANALYZING"],
      ANALYZING: ["NEEDS_REVIEW", "APPROVED"],
      NEEDS_REVIEW: ["APPROVED", "REJECTED"],
      APPROVED: ["ACTIVE"],
      REJECTED: ["DRAFT"],
    };
=======
    const validTransitions = {
      DRAFT: ["PENDING_MATCH", "PENDING_INSTITUTION", "ANALYZING"],
      PENDING_MATCH: ["PENDING_INSTITUTION", "DRAFT"],
      PENDING_INSTITUTION: ["PENDING_COORDINATOR", "DRAFT", "ANALYZING"],
      PENDING_COORDINATOR: ["ACTIVE", "DRAFT", "ANALYZING"],
      ANALYZING: ["NEEDS_REVIEW", "REJECTED"],
      NEEDS_REVIEW: ["APPROVED", "PENDING_COORDINATOR", "ACTIVE", "REJECTED"],
      APPROVED: ["ACTIVE", "EVALUATION", "CLOSED"],
      ACTIVE: ["EVALUATION", "CLOSED"],
      EVALUATION: ["CLOSED"],
      CLOSED: ["FINAL_EXAM"],
      REJECTED: ["DRAFT"]
    };
>>>>>>> REPLACE
